### ISSUE TITLE
datatable use of literal causes $watch error

### ISSUE THREAD

**Issue by Bochenski** [GoIncremental/gi-ui#1]
For example, using this in a literal:

<label class="literal"><a class="btn btn-info" target="_blank" ng-href="/reports/jobsheet/{{item._id}}">blah</a></label>

causes angular to barf on page initialisation:

TypeError: Object [object Object] has no method '$watch'
    at attrInterpolateLinkFn (http://dev.gb3.co.uk:3005/js/libs/angular.js:4996:13)
    at nodeLinkFn (http://dev.gb3.co.uk:3005/js/libs/angular.js:4774:13)
    at compositeLinkFn (http://dev.gb3.co.uk:3005/js/libs/angular.js:4365:15)
    at compositeLinkFn (http://dev.gb3.co.uk:3005/js/libs/angular.js:4368:13)
    at compositeLinkFn (http://dev.gb3.co.uk:3005/js/libs/angular.js:4368:13)
    at publicLinkFn (http://dev.gb3.co.uk:3005/js/libs/angular.js:4270:30)
    at Object.compile (http://dev.gb3.co.uk:3005/js/libs/gint-ui.js:64:9)
    at applyDirectivesToNode (http://dev.gb3.co.uk:3005/js/libs/angular.js:4588:32)
    at http://dev.gb3.co.uk:3005/js/libs/angular.js:4896:37
    at http://dev.gb3.co.uk:3005/js/libs/angular.js:9782:11 <a class="btn btn-info" target="_blank" ng-href="/reports/jobsheet/{{item._id}}">

**Comment by Bochenski** [comment]
Closing as part of an org-wide issue tidy-up: this project is no longer active. Not planned.
